CREATE TABLE IF NOT EXISTS products (
                          id INTEGER GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
                          title VARCHAR(255) NOT NULL,
                          vendor VARCHAR(255),
                          product_type VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS variants (
                          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          product_id INTEGER NOT NULL,

                          title VARCHAR(255),
                          option1 VARCHAR(255),
                          option2 VARCHAR(255),
                          option3 VARCHAR(255),

                          available BOOLEAN,
                          price NUMERIC(10,2),

                          CONSTRAINT fk_product
                              FOREIGN KEY(product_id)
                                  REFERENCES products(id)
                                  ON DELETE CASCADE
);

CREATE INDEX idx_variants_product_id ON variants(product_id);